PPWS6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.tambahKegiatan, name='tambahKegiatan'),
    path('tambahPeserta/<int:id>/', views.tambahPeserta, name='tambahPeserta'),
    path('daftarkegiatan/', views.daftarKegiatan, name='daftarkegiatan'),
    
]

main/models.py
# Create your models here.
from django.db import models

# Create your models here.
class Kegiatan (models.Model):
    event 	= models.CharField(max_length=50,null=False,blank=False)

    def _str_(self):
        return self.event

class Peserta(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete = models.CASCADE,null=False)
    register = models.CharField(max_length=50)
    
    def _str_(self):
        return self.register
  

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Kegiatan, Peserta
from django.db.utils import OperationalError

class Input_Form(forms.ModelForm):
	class Meta:
		model = Kegiatan
		fields = [
		'event'
		]

		labels = {
			'event' : 'Nama Kegiatan',
		}

		widgets = {
			'event' : forms.TextInput(
				attrs = {
					'class' : 'form-control',
					'placeholder' : 'Masukkan nama event',}
				)
		}

class Registration(forms.ModelForm):
	class Meta:
		model = Peserta
		fields = [
		'register',

		]

		labels = {
			'register' : 'Nama Lengkap',

		}

		widgets = {
			'register' : forms.TextInput(
				attrs = {
					'class' : 'form-control',
					'placeholder' : 'Masukkan nama Anda',}
				),


		}

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Input_Form, Registration
from .models import Kegiatan, Peserta


def tambahKegiatan(request):
	posts_kegiatan = Input_Form(request.POST or None)
	if posts_kegiatan.is_valid():
		posts_kegiatan.save()
		posts_kegiatan = Input_Form()
	context = {

		'form' : posts_kegiatan,
	}	
	return render(request,'main/create.html',context)
		
def tambahPeserta(request,id):
	posts_peserta = Registration(request.POST or None)
	if posts_peserta.is_valid():
		aktivitas = Kegiatan.objects.get(id=id)
		Peserta.objects.create(register = request.POST['register'], kegiatan=aktivitas)
		posts_peserta = Registration()
	context = {

		'form' : posts_peserta,
	}

	return render (request, 'main/form_peserta.html', context)
	
def daftarKegiatan(request):
	kegiatan = Kegiatan.objects.all()
	peserta = Peserta.objects.all()
	context = {

		'kegiatan' : kegiatan,
		'peserta' : peserta,
	}

	return render (request, 'main/daftar.html', context)

main/templates/main/create.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block content %}
<div class="card" style="width: 18rem;">
  
  <div class="card-body">
  <form method='POST'>
    {% csrf_token %} {{ form.as_p }}
    <input type='submit' value='Tambah' style="background-color: #b17b45;" />
  </form>
 
  </div>
</div>
{% endblock %}

main/templates/main/daftar.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block content %}
{%for k in kegiatan%} 

<div class="card" style="width: 18rem;">
    <div class="card-header justify-content-center" style="text-align: center;">{{k.event}}</div>
    <div class="card-body">
        <table>
            {% for p in peserta %} {% if p.kegiatan.event == k.event %}
            <p class="card-text">{{p.register}}</p>
            {% endif %} {% endfor %}
        </table>
     </div>
     <a class="btn btn-secondary" role="button" href = "{% url 'main:tambahPeserta' k.id %}" >Tambah Peserta</a> 

</div>

{%endfor%}

{% endblock %}

main/templates/main/form_peserta.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block content %}
<div class="card" style="width: 18rem;">
  
  <div class="card-body">
  <form method='POST'>
    {% csrf_token %} {{ form.as_p }}
    <input type='submit' value='Tambah' style="background-color: #b17b45;" />
  </form>
 
  </div>
</div>
{% endblock %}